@host=http://localhost:5192

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Laura",
    "lastName": "Bte",
    "email": "laura@gmail.com",
    "password": "1234"
}

### separation between requests

